apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: compact-url

type: Opaque

stringData:
  POSTGRES_DB: compacturldb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres123